# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2025-01-22 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0003_auto_20250120_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(default='', upload_to='mascota/images/'),
            preserve_default=False,
        ),
    ]
