# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2025-01-22 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0007_auto_20250122_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(blank=True, default='', upload_to='mascotas'),
            preserve_default=False,
        ),
    ]
