# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2025-01-22 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0008_auto_20250122_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(upload_to='mascotas'),
        ),
    ]
